services:
  service-two:
    image: quay.io/rh_ee_sshirodk/demo-service-two
    ports:
      - 8081:8081
    container_name: service-two
    depends_on:
      - postgres
    environment:
      - quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - 5432:5432